### ISSUE TITLE
ModuleNotFoundError: No module named 'shapely'

### ISSUE THREAD

**Issue by mattdesl** [ximinng/VectorFusion-pytorch#2]
Note that after installation and when trying to render (MacOS M2), I received this error:

```sh
Traceback (most recent call last):
  File "/Users/matt/prj/VectorFusion-pytorch/run_painterly_render.py", line 113, in <module>
    main(args, seed_range)
  File "/Users/matt/prj/VectorFusion-pytorch/run_painterly_render.py", line 44, in main
    from pipelines.painter.VectorFusion_pipeline import VectorFusionPipeline
  File "/Users/matt/prj/VectorFusion-pytorch/pipelines/painter/VectorFusion_pipeline.py", line 17, in <module>
    from methods.painter.vectorfusion import LSDSPipeline, LSDSSDXLPipeline, Painter, PainterOptimizer
  File "/Users/matt/prj/VectorFusion-pytorch/methods/painter/vectorfusion/__init__.py", line 8, in <module>
    from .painter_params import Painter, PainterOptimizer
  File "/Users/matt/prj/VectorFusion-pytorch/methods/painter/vectorfusion/painter_params.py", line 11, in <module>
    from shapely.geometry.polygon import Polygon
ModuleNotFoundError: No module named 'shapely'
```

The following seems to have resolved things:

```sh
conda install -c conda-forge shapely
```

**Comment by ximinng** [comment]
Yes, we neglected to remember this dependency. Thank you for reminding us！

or 

```bash
pip install shapely
```
